{
 "title": "Debezium MySQL Connector",
 "description": "Monitoring Dashboard for Debezium MySQL connector. ",
 "tags": [
  "mysql",
  "debezium"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "MySQL Node",
    "query": {
     "query": "debezium_metrics_binlogposition"
    }
   },
   {
    "name": "instance",
    "label": "Connector Node",
    "query": {
     "query": "debezium_metrics_binlogposition"
    }
   },
   {
    "name": "context",
    "label": "context",
    "query": {
     "query": "debezium_metrics_millisecondssincelastevent"
    }
   },
   {
    "name": "plugin",
    "label": "plugin",
    "query": {
     "query": "debezium_metrics_binlogposition"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Binlog Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "\n# Debezium MySQL Connector Metrics\n\nThe Debezium MySQL connector has three metric types in addition to the built-in support for JMX metrics that Zookeeper, Kafka, and Kafka Connect have.\n\n* snapshot metrics\n\n* binlog metrics\n\n* schema history metrics\n\nFor more detailed informarion about the metrics please visit the Debezium documentation page\n\n[Click here to visit](https://debezium.io/documentation/reference/1.0/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.html#mysql-connector-binlog-metrics)\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_connected{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Binlog Position",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_binlogposition{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "GTID Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_isgtidmodeenabled{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Committed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofcommittedtransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf RolledBack Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofrolledbacktransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Not WellFormed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofnotwellformedtransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Total NumberOf EventsSeen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Skipped Events",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofskippedevents{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Events Filtered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofeventsfiltered{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "MilliSeconds Since LastEvent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastevent{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queuetotalcapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Seconds Behind Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_SecondsBehindMaster{context=\"$context\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "MilliSeconds Behind Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_millisecondsbehindsource{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Disconnects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_numberofdisconnects{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Large Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_numberoflargetransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Tablecount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totaltablecount{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Remaining Tales",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_remainingtablecount{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Holding GlobalLock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_holdinggloballock{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotrunning{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotaborted{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotcompleted{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotdurationinseconds{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Events Filtered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_numberofeventsfiltered{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "MilliSeconds Since LastEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastevent{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queuetotalcapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "NumberOf Erroneous Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_numberoferroneousevents{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Total NumberOf Events Seen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Schema History Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metric Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "options": {
    "content": "\n# Schema Changes Metrics\n\nFor detailed explanation for all the schema changes metrics: [Visit Debezium documentation](https://debezium.io/documentation/reference/1.0/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.html#mysql-connector-schema-history-metrics)\n\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Recovery StartTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_recoverystarttime{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Since Last AppliedChange",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastappliedchange{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Since Last RecoveredChange",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastrecoveredchange{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Changes Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_changesrecovered{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_changesapplied{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  }
 ]
}