apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: connect-metrics
  namespace: kafka
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: kafka-connect
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
    interval: 15s
