kind: ConfigMap
apiVersion: v1
metadata:
  name: connect-metrics
  namespace: kafka
data:
  config.yaml: |
    lowercaseOutputName: true
    rules:
    - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), key=([^>]+)><>([^:]+)"
      name: "debezium_metrics_$5"
      labels:
        plugin: "$1"
        name: "$3"
        context: "$2"
        key: "$4"
    - pattern: "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "kafka_connect_worker_$1"
    - pattern: "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      name: "kafka_connect_client_$2"
      labels:
        client_id: "$1"
